In [1]:
import torch
import einops
from components import MLP, gelu, Attention
import plotly.express as px

In [2]:
d_model = 512
n_blocks = 4


x = torch.randn(d_model)
x

tensor([ 5.3588e-01,  2.7836e-01,  2.1012e-01, -3.2278e-01, -2.5077e-01,
        -8.0893e-01,  3.5546e-01,  1.2668e-01, -9.7755e-01, -2.9378e-01,
        -8.2771e-01,  2.7987e-01, -2.6463e-01,  1.3395e+00, -3.4597e-01,
         1.0350e+00, -8.0333e-01, -8.4626e-01, -5.5391e-01,  7.5343e-01,
        -1.3241e+00, -5.4970e-02, -1.1731e+00,  4.0304e-01,  2.8821e-01,
         5.4903e-01,  7.2470e-01, -1.5225e-01,  5.3463e-01,  1.2470e+00,
        -6.7454e-02,  1.3087e+00,  6.4573e-01,  2.6164e-01, -3.3966e+00,
        -3.3643e-01, -3.0609e+00, -5.8442e-01,  3.2402e-01, -1.1047e+00,
        -1.3437e+00,  3.8046e-01, -2.7802e+00,  1.8281e-03, -8.2781e-01,
         2.0626e-02, -1.2016e-01, -1.0118e+00,  6.6390e-01,  3.5294e-02,
         1.1080e-01,  1.1971e+00,  1.6873e+00,  4.3685e-01, -3.0011e-01,
         1.9617e-01,  3.7858e-01,  6.7845e-01,  1.3687e+00, -8.8605e-01,
         8.8634e-01, -8.9570e-01, -2.8954e-01, -7.7142e-01, -9.8172e-01,
         5.1553e-02, -2.2298e+00,  2.3812e-01, -1.7

In [3]:
mlp = MLP(d_in = d_model, d_mlp=d_model*4)

In [4]:
out = mlp(x)
print(out.shape)
print(out)

torch.Size([512])
tensor([-1.6255,  1.8677, -0.2144,  0.5649, -1.8868, -2.3716, -0.2275,  2.0085,
         0.5103, -1.1750,  2.2774, -0.6122, -0.1155,  1.1690,  1.6062,  0.1082,
        -0.2446,  1.3545,  1.2614, -1.7180,  0.6219,  0.2920, -0.8657,  2.2784,
        -1.1381, -2.6706,  1.8789, -1.9868,  0.7416,  0.2704,  2.1508,  0.1825,
         0.2113, -2.6888, -1.1679,  1.6086,  2.2268, -0.9930, -2.1332,  3.0611,
         0.4075,  1.7474,  0.0253,  0.0581, -2.9700, -2.1044,  1.2171, -0.1791,
         2.4567, -0.9948, -0.9901, -0.9341, -0.4304, -1.0333, -0.0572,  1.4482,
        -0.6537, -1.2552,  0.8795, -0.9543,  0.0213, -2.2355,  1.1841, -0.7437,
         0.0669, -1.7504, -2.1191, -1.0907, -1.4912,  1.7225, -1.6555, -3.0508,
         1.4650, -3.1064, -0.8977, -2.1852, -1.6473,  0.6664,  0.5695,  2.3661,
         2.5642, -1.0780,  1.2694, -4.2680, -3.1609,  1.1143,  0.0883,  0.9036,
         0.1473,  1.2115,  0.3184,  0.2412,  2.9573,  0.6428, -0.2999,  0.4999,
        -0.8538,  0.60

In [5]:
a = torch.randn(2,3,4)
b = torch.randn(2,3,4)
res = einops.einsum(a, b, "... id, ... id -> ...")
print(res)


tensor([[ 0.5255, -3.5496, -0.3981],
        [-0.9397, -5.6702,  0.2862]])


In [6]:
print(res.shape)

torch.Size([2, 3])


In [7]:
torch.dot(a[0][0], b[0][0])

tensor(0.5255)

In [8]:
x = torch.linspace(-5, 5, 100)
fig = px.line(x=x, y=gelu(x))
fig.show()

In [9]:
attn = Attention(512, 8)
x = torch.randn(4, 5, 512)

scores = attn(x)
print(scores.shape)


tensor([[-0.0000e+00, -1.0000e+09, -1.0000e+09, -1.0000e+09, -1.0000e+09],
        [-0.0000e+00, -0.0000e+00, -1.0000e+09, -1.0000e+09, -1.0000e+09],
        [-0.0000e+00, -0.0000e+00, -0.0000e+00, -1.0000e+09, -1.0000e+09],
        [-0.0000e+00, -0.0000e+00, -0.0000e+00, -0.0000e+00, -1.0000e+09],
        [-0.0000e+00, -0.0000e+00, -0.0000e+00, -0.0000e+00, -0.0000e+00]])
torch.Size([4, 8, 5, 5])


In [11]:
px.imshow(scores[0, 0, :, :].detach(), color_continuous_scale="RdBu", color_continuous_midpoint=0)