In [1]:
import torch
import einops
from components import MLP, gelu, Attention, LayerNorm, TransformerBlock
import plotly.express as px

In [2]:
d_model = 512
n_blocks = 4


x = torch.randn(d_model)
x

tensor([ 0.4479,  0.1569,  0.2038,  0.9539,  0.5990, -1.6825, -1.4722,  0.0792,
         1.0956,  0.6856, -0.5499,  1.1455, -0.0047,  0.8734, -0.9120, -1.1448,
         0.4739, -0.9176, -0.2635,  0.6401,  0.9538,  1.3646,  0.5168, -0.2817,
         0.7642, -0.5465,  2.0140,  0.9677, -0.8238, -0.7613, -1.5969, -0.9926,
        -0.5834,  0.3316, -0.6453, -0.6775,  1.8970,  0.7451, -0.1410,  1.0932,
        -0.9751, -0.9105,  0.5710,  0.7793,  0.3123,  0.1888,  0.9829, -0.6785,
         1.0087, -0.0615, -0.5046,  0.1464,  0.9171,  0.4779, -0.9163,  0.5349,
         0.0818,  1.8231,  0.6619, -2.4707, -0.3822, -0.9436, -1.9529,  0.9907,
        -0.7303, -0.0274, -2.0182, -1.2011, -0.1905,  0.0944,  0.6649,  0.2957,
         0.3437, -1.5386, -0.7910,  0.6510,  0.5824, -0.8778, -3.2588,  0.2279,
         0.1853,  0.1142, -0.1936,  0.5073, -2.3643,  0.1947,  0.6250,  0.8045,
        -2.0213,  0.4134,  0.6323, -0.8599, -0.1489,  0.0200, -1.6755,  0.2581,
        -0.1397,  2.4069,  1.3330,  0.80

In [3]:
mlp = MLP(d_in = d_model, d_mlp=d_model*4)

In [4]:
out = mlp(x)
print(out.shape)
print(out)

torch.Size([512])
tensor([ 5.6565e-01,  2.9323e+00,  1.7325e+00, -8.7273e-01,  4.3705e-01,
        -1.9301e+00, -4.8434e-01,  4.0544e-01,  7.8530e-01, -7.3179e-01,
        -4.2232e-01, -2.0746e+00,  3.9211e-01, -1.4916e-02, -8.1347e-01,
         3.1280e-01, -1.4842e+00, -1.2693e-01,  4.7338e-01, -5.8229e-01,
         1.0324e+00,  1.9474e+00,  1.8242e+00,  1.0093e+00,  6.7316e-01,
        -9.8190e-01,  4.0308e-01,  1.9463e+00,  6.7254e-01,  1.8818e+00,
        -4.6431e-01, -1.1447e+00,  9.9556e-01,  1.5640e+00,  1.6083e+00,
         2.8466e-01,  2.5791e-01,  7.1341e-01, -1.3227e+00,  2.0499e+00,
         6.9662e-01,  1.6635e+00, -9.2643e-01,  1.4521e+00,  1.8989e+00,
        -1.1703e+00,  5.8432e-01,  1.2954e+00,  1.9214e-01,  2.9604e-01,
         1.1285e+00, -2.9765e-01,  2.3581e+00, -1.1090e+00,  1.4007e+00,
         2.2612e-01, -8.5873e-01,  2.9680e-01, -2.2174e-01,  1.1359e+00,
         4.8469e-01,  4.9680e-01, -8.1570e-01,  4.5951e-01, -8.5607e-01,
         8.6374e-01, -2.3348e+00,

In [5]:
a = torch.randn(2,3,4)
b = torch.randn(2,3,4)
res = einops.einsum(a, b, "... id, ... id -> ...")
print(res)


tensor([[1.1062, 0.2172, 2.5370],
        [0.6779, 0.5613, 2.5569]])


In [6]:
print(res.shape)

torch.Size([2, 3])


In [7]:
torch.dot(a[0][0], b[0][0])

tensor(1.1062)

In [8]:
x = torch.linspace(-5, 5, 100)
fig = px.line(x=x, y=gelu(x))
fig.show()

In [9]:
attn = Attention(512, 8)
x = torch.randn(4, 5, 512)

out = attn(x)
print('asdf')
print(out.shape)


asdf
torch.Size([4, 5, 512])


In [12]:
# px.imshow(out[0].detach(), color_continuous_scale="RdBu", color_continuous_midpoint=0)

In [11]:
out[0, :, :]

tensor([[ -4.9118,  -0.2502, -31.9146,  ...,  11.6065,   4.0172,  19.8031],
        [  3.5613,  -6.3568, -10.1047,  ...,  16.9608,  -1.9817,  29.8813],
        [  1.9877,   0.8436, -15.2947,  ...,   8.8545,  -4.7227,  18.9275],
        [ -4.2332,   9.2067, -19.8856,  ...,  -4.3783, -11.3493,  -3.3997],
        [ -4.6193,  -3.7581,  17.0726,  ...,  13.5476, -17.1035,   7.6037]],
       grad_fn=<SliceBackward0>)

In [17]:
torch.sqrt(torch.ones(4)**2).sum(-1)

tensor(4.)

In [3]:
block = TransformerBlock(d_model=512)
x = torch.randn(4, 5, 512)

out = block(x)
print(out.shape)

RuntimeError: The size of tensor a (512) must match the size of tensor b (5) at non-singleton dimension 2